//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("argencatModel", "FK_student_course_paymentplan_courses", "cours", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ArgenCatProj.Model.course), "student_course_paymentplan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ArgenCatProj.Model.student_course_paymentplan), true)]
[assembly: EdmRelationshipAttribute("argencatModel", "FK_paymentplan_payments_paymentplans", "paymentplan", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ArgenCatProj.Model.paymentplan), "paymentplan_payments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ArgenCatProj.Model.paymentplan_payments), true)]
[assembly: EdmRelationshipAttribute("argencatModel", "FK_paymentplan_payments_payments", "payment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ArgenCatProj.Model.payment), "paymentplan_payments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ArgenCatProj.Model.paymentplan_payments), true)]
[assembly: EdmRelationshipAttribute("argencatModel", "FK_student_course_paymentplan_paymentplans", "paymentplan", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ArgenCatProj.Model.paymentplan), "student_course_paymentplan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ArgenCatProj.Model.student_course_paymentplan), true)]
[assembly: EdmRelationshipAttribute("argencatModel", "FK_student_course_paymentplan_students", "student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ArgenCatProj.Model.student), "student_course_paymentplan", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ArgenCatProj.Model.student_course_paymentplan), true)]

#endregion

namespace ArgenCatProj.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class argencatEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new argencatEntities object using the connection string found in the 'argencatEntities' section of the application configuration file.
        /// </summary>
        public argencatEntities() : base("name=argencatEntities", "argencatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new argencatEntities object.
        /// </summary>
        public argencatEntities(string connectionString) : base(connectionString, "argencatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new argencatEntities object.
        /// </summary>
        public argencatEntities(EntityConnection connection) : base(connection, "argencatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<course> courses
        {
            get
            {
                if ((_courses == null))
                {
                    _courses = base.CreateObjectSet<course>("courses");
                }
                return _courses;
            }
        }
        private ObjectSet<course> _courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<paymentplan_payments> paymentplan_payments
        {
            get
            {
                if ((_paymentplan_payments == null))
                {
                    _paymentplan_payments = base.CreateObjectSet<paymentplan_payments>("paymentplan_payments");
                }
                return _paymentplan_payments;
            }
        }
        private ObjectSet<paymentplan_payments> _paymentplan_payments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<paymentplan> paymentplans
        {
            get
            {
                if ((_paymentplans == null))
                {
                    _paymentplans = base.CreateObjectSet<paymentplan>("paymentplans");
                }
                return _paymentplans;
            }
        }
        private ObjectSet<paymentplan> _paymentplans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<payment> payments
        {
            get
            {
                if ((_payments == null))
                {
                    _payments = base.CreateObjectSet<payment>("payments");
                }
                return _payments;
            }
        }
        private ObjectSet<payment> _payments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student_course_paymentplan> student_course_paymentplan
        {
            get
            {
                if ((_student_course_paymentplan == null))
                {
                    _student_course_paymentplan = base.CreateObjectSet<student_course_paymentplan>("student_course_paymentplan");
                }
                return _student_course_paymentplan;
            }
        }
        private ObjectSet<student_course_paymentplan> _student_course_paymentplan;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<student> students
        {
            get
            {
                if ((_students == null))
                {
                    _students = base.CreateObjectSet<student>("students");
                }
                return _students;
            }
        }
        private ObjectSet<student> _students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocourses(course course)
        {
            base.AddObject("courses", course);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the paymentplan_payments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopaymentplan_payments(paymentplan_payments paymentplan_payments)
        {
            base.AddObject("paymentplan_payments", paymentplan_payments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the paymentplans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopaymentplans(paymentplan paymentplan)
        {
            base.AddObject("paymentplans", paymentplan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the payments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopayments(payment payment)
        {
            base.AddObject("payments", payment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the student_course_paymentplan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudent_course_paymentplan(student_course_paymentplan student_course_paymentplan)
        {
            base.AddObject("student_course_paymentplan", student_course_paymentplan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostudents(student student)
        {
            base.AddObject("students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="argencatModel", Name="course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class course : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new course object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="paymentsCount">Initial value of the PaymentsCount property.</param>
        public static course Createcourse(global::System.Int32 id, global::System.String name, global::System.Int32 paymentsCount)
        {
            course course = new course();
            course.Id = id;
            course.Name = name;
            course.PaymentsCount = paymentsCount;
            return course;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaymentsCount
        {
            get
            {
                return _PaymentsCount;
            }
            set
            {
                OnPaymentsCountChanging(value);
                ReportPropertyChanging("PaymentsCount");
                _PaymentsCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentsCount");
                OnPaymentsCountChanged();
            }
        }
        private global::System.Int32 _PaymentsCount;
        partial void OnPaymentsCountChanging(global::System.Int32 value);
        partial void OnPaymentsCountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_student_course_paymentplan_courses", "student_course_paymentplan")]
        public EntityCollection<student_course_paymentplan> student_course_paymentplan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<student_course_paymentplan>("argencatModel.FK_student_course_paymentplan_courses", "student_course_paymentplan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<student_course_paymentplan>("argencatModel.FK_student_course_paymentplan_courses", "student_course_paymentplan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="argencatModel", Name="payment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class payment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new payment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="payed">Initial value of the Payed property.</param>
        public static payment Createpayment(global::System.Int32 id, global::System.Int32 number, global::System.Int32 payed)
        {
            payment payment = new payment();
            payment.Id = id;
            payment.Number = number;
            payment.Payed = payed;
            return payment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Payed
        {
            get
            {
                return _Payed;
            }
            set
            {
                OnPayedChanging(value);
                ReportPropertyChanging("Payed");
                _Payed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Payed");
                OnPayedChanged();
            }
        }
        private global::System.Int32 _Payed;
        partial void OnPayedChanging(global::System.Int32 value);
        partial void OnPayedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Single> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Single> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DatePayed
        {
            get
            {
                return _DatePayed;
            }
            set
            {
                OnDatePayedChanging(value);
                ReportPropertyChanging("DatePayed");
                _DatePayed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatePayed");
                OnDatePayedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DatePayed;
        partial void OnDatePayedChanging(Nullable<global::System.DateTime> value);
        partial void OnDatePayedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RecipNumber
        {
            get
            {
                return _RecipNumber;
            }
            set
            {
                OnRecipNumberChanging(value);
                ReportPropertyChanging("RecipNumber");
                _RecipNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecipNumber");
                OnRecipNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _RecipNumber;
        partial void OnRecipNumberChanging(Nullable<global::System.Int32> value);
        partial void OnRecipNumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_paymentplan_payments_payments", "paymentplan_payments")]
        public EntityCollection<paymentplan_payments> paymentplan_payments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<paymentplan_payments>("argencatModel.FK_paymentplan_payments_payments", "paymentplan_payments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<paymentplan_payments>("argencatModel.FK_paymentplan_payments_payments", "paymentplan_payments", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="argencatModel", Name="paymentplan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paymentplan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new paymentplan object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static paymentplan Createpaymentplan(global::System.Int32 id, global::System.String name)
        {
            paymentplan paymentplan = new paymentplan();
            paymentplan.Id = id;
            paymentplan.Name = name;
            return paymentplan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_paymentplan_payments_paymentplans", "paymentplan_payments")]
        public EntityCollection<paymentplan_payments> paymentplan_payments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<paymentplan_payments>("argencatModel.FK_paymentplan_payments_paymentplans", "paymentplan_payments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<paymentplan_payments>("argencatModel.FK_paymentplan_payments_paymentplans", "paymentplan_payments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_student_course_paymentplan_paymentplans", "student_course_paymentplan")]
        public EntityCollection<student_course_paymentplan> student_course_paymentplan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<student_course_paymentplan>("argencatModel.FK_student_course_paymentplan_paymentplans", "student_course_paymentplan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<student_course_paymentplan>("argencatModel.FK_student_course_paymentplan_paymentplans", "student_course_paymentplan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="argencatModel", Name="paymentplan_payments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paymentplan_payments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new paymentplan_payments object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="paymentplanId">Initial value of the paymentplanId property.</param>
        /// <param name="paymentId">Initial value of the paymentId property.</param>
        public static paymentplan_payments Createpaymentplan_payments(global::System.Int32 id, global::System.Int32 paymentplanId, global::System.Int32 paymentId)
        {
            paymentplan_payments paymentplan_payments = new paymentplan_payments();
            paymentplan_payments.Id = id;
            paymentplan_payments.paymentplanId = paymentplanId;
            paymentplan_payments.paymentId = paymentId;
            return paymentplan_payments;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 paymentplanId
        {
            get
            {
                return _paymentplanId;
            }
            set
            {
                OnpaymentplanIdChanging(value);
                ReportPropertyChanging("paymentplanId");
                _paymentplanId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paymentplanId");
                OnpaymentplanIdChanged();
            }
        }
        private global::System.Int32 _paymentplanId;
        partial void OnpaymentplanIdChanging(global::System.Int32 value);
        partial void OnpaymentplanIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 paymentId
        {
            get
            {
                return _paymentId;
            }
            set
            {
                OnpaymentIdChanging(value);
                ReportPropertyChanging("paymentId");
                _paymentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paymentId");
                OnpaymentIdChanged();
            }
        }
        private global::System.Int32 _paymentId;
        partial void OnpaymentIdChanging(global::System.Int32 value);
        partial void OnpaymentIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_paymentplan_payments_paymentplans", "paymentplan")]
        public paymentplan paymentplan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paymentplan>("argencatModel.FK_paymentplan_payments_paymentplans", "paymentplan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paymentplan>("argencatModel.FK_paymentplan_payments_paymentplans", "paymentplan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<paymentplan> paymentplanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paymentplan>("argencatModel.FK_paymentplan_payments_paymentplans", "paymentplan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<paymentplan>("argencatModel.FK_paymentplan_payments_paymentplans", "paymentplan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_paymentplan_payments_payments", "payment")]
        public payment payment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<payment>("argencatModel.FK_paymentplan_payments_payments", "payment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<payment>("argencatModel.FK_paymentplan_payments_payments", "payment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<payment> paymentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<payment>("argencatModel.FK_paymentplan_payments_payments", "payment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<payment>("argencatModel.FK_paymentplan_payments_payments", "payment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="argencatModel", Name="student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="dni">Initial value of the Dni property.</param>
        public static student Createstudent(global::System.Int32 id, global::System.Int32 number, global::System.String name, global::System.String dni)
        {
            student student = new student();
            student.Id = id;
            student.Number = number;
            student.Name = name;
            student.Dni = dni;
            return student;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Dni
        {
            get
            {
                return _Dni;
            }
            set
            {
                OnDniChanging(value);
                ReportPropertyChanging("Dni");
                _Dni = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Dni");
                OnDniChanged();
            }
        }
        private global::System.String _Dni;
        partial void OnDniChanging(global::System.String value);
        partial void OnDniChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone2
        {
            get
            {
                return _Phone2;
            }
            set
            {
                OnPhone2Changing(value);
                ReportPropertyChanging("Phone2");
                _Phone2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone2");
                OnPhone2Changed();
            }
        }
        private global::System.String _Phone2;
        partial void OnPhone2Changing(global::System.String value);
        partial void OnPhone2Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_student_course_paymentplan_students", "student_course_paymentplan")]
        public EntityCollection<student_course_paymentplan> student_course_paymentplan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<student_course_paymentplan>("argencatModel.FK_student_course_paymentplan_students", "student_course_paymentplan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<student_course_paymentplan>("argencatModel.FK_student_course_paymentplan_students", "student_course_paymentplan", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="argencatModel", Name="student_course_paymentplan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class student_course_paymentplan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new student_course_paymentplan object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="studentId">Initial value of the studentId property.</param>
        /// <param name="courseId">Initial value of the courseId property.</param>
        /// <param name="paymentPlanId">Initial value of the paymentPlanId property.</param>
        public static student_course_paymentplan Createstudent_course_paymentplan(global::System.Int32 id, global::System.Int32 studentId, global::System.Int32 courseId, global::System.Int32 paymentPlanId)
        {
            student_course_paymentplan student_course_paymentplan = new student_course_paymentplan();
            student_course_paymentplan.Id = id;
            student_course_paymentplan.studentId = studentId;
            student_course_paymentplan.courseId = courseId;
            student_course_paymentplan.paymentPlanId = paymentPlanId;
            return student_course_paymentplan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                OnstudentIdChanging(value);
                ReportPropertyChanging("studentId");
                _studentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("studentId");
                OnstudentIdChanged();
            }
        }
        private global::System.Int32 _studentId;
        partial void OnstudentIdChanging(global::System.Int32 value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 courseId
        {
            get
            {
                return _courseId;
            }
            set
            {
                OncourseIdChanging(value);
                ReportPropertyChanging("courseId");
                _courseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("courseId");
                OncourseIdChanged();
            }
        }
        private global::System.Int32 _courseId;
        partial void OncourseIdChanging(global::System.Int32 value);
        partial void OncourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 paymentPlanId
        {
            get
            {
                return _paymentPlanId;
            }
            set
            {
                OnpaymentPlanIdChanging(value);
                ReportPropertyChanging("paymentPlanId");
                _paymentPlanId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paymentPlanId");
                OnpaymentPlanIdChanged();
            }
        }
        private global::System.Int32 _paymentPlanId;
        partial void OnpaymentPlanIdChanging(global::System.Int32 value);
        partial void OnpaymentPlanIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_student_course_paymentplan_courses", "cours")]
        public course course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<course>("argencatModel.FK_student_course_paymentplan_courses", "cours").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<course>("argencatModel.FK_student_course_paymentplan_courses", "cours").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<course> courseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<course>("argencatModel.FK_student_course_paymentplan_courses", "cours");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<course>("argencatModel.FK_student_course_paymentplan_courses", "cours", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_student_course_paymentplan_paymentplans", "paymentplan")]
        public paymentplan paymentplan
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paymentplan>("argencatModel.FK_student_course_paymentplan_paymentplans", "paymentplan").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paymentplan>("argencatModel.FK_student_course_paymentplan_paymentplans", "paymentplan").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<paymentplan> paymentplanReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<paymentplan>("argencatModel.FK_student_course_paymentplan_paymentplans", "paymentplan");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<paymentplan>("argencatModel.FK_student_course_paymentplan_paymentplans", "paymentplan", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("argencatModel", "FK_student_course_paymentplan_students", "student")]
        public student student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<student>("argencatModel.FK_student_course_paymentplan_students", "student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<student>("argencatModel.FK_student_course_paymentplan_students", "student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<student> studentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<student>("argencatModel.FK_student_course_paymentplan_students", "student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<student>("argencatModel.FK_student_course_paymentplan_students", "student", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="argencatModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="pass">Initial value of the Pass property.</param>
        public static user Createuser(global::System.Int32 id, global::System.String name, global::System.String pass)
        {
            user user = new user();
            user.Id = id;
            user.Name = name;
            user.Pass = pass;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private global::System.String _Pass;
        partial void OnPassChanging(global::System.String value);
        partial void OnPassChanged();

        #endregion
    
    }

    #endregion
    
}
